project:
  type: website

website:
  title: "shardul's blog"
  site-url: https://sharduljunagade.github.io/blog/
  description: "shardul's blog"
  navbar:
    right:
      # - about.qmd
      - text: about
        href: https://sharduljunagade.github.io/
      - text: blog
        href: https://sharduljunagade.github.io/blog/
      - text: projects
        href: https://sharduljunagade.github.io/projects/
      - text: repositories
        href: https://sharduljunagade.github.io/repositories/
      - text: cv
        href: https://sharduljunagade.github.io/cv/
      - icon: github
        href: https://github.com/ShardulJunagade/blog
      - icon: linkedin
        href: https://www.linkedin.com/in/shardul-junagade/
      - icon: twitter-x
        href: https://twitter.com/Sh4rdulX
      - icon: rss
        href: index.xml
      # - icon: rss
      #   href: index.xml
  search:
    keyboard-shortcut: [/, s, f]
format:
  html:
    smooth-scroll: true
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Poppins" type="text/css"/>
    mainfont: Poppins, sans-serif
    # monofont: JetBrainsMono, monospace (not needed)

execute:
  freeze: auto

