project:
  type: website

website:
  title: "shardul's blog"
  site-url: https://sharduljunagade.github.io/blog/
  description: "shardul's blog"
  navbar:
    right:
      # - about.qmd
      - text: about
        href: https://sharduljunagade.github.io/
      - text: blog
        href: https://sharduljunagade.github.io/blog/
      - text: projects
        href: https://sharduljunagade.github.io/projects/
      - text: repositories
        href: https://sharduljunagade.github.io/repositories/
      - text: cv
        href: https://sharduljunagade.github.io/cv/
      - icon: github
        href: https://github.com/ShardulJunagade/blog
      - icon: linkedin
        href: https://www.linkedin.com/in/shardul-junagade/
      - icon: twitter-x
        href: https://twitter.com/Sh4rdulX
      - icon: rss
        href: index.xml
      # - icon: rss
      #   href: index.xml
  search:
    keyboard-shortcut: [/, s, f]
  page-footer:
    left:
      - text: "<span class='footer-name'>Shardul Junagade © 2025.</span><br><span class='footer-sub'>This website was designed and made by me using <a href='https://quarto.org/' target='_blank'>Quarto</a> and hosted using <a href='https://pages.github.com/' target='_blank'>GitHub Pages</a>!</span>"
    right:
      - text: "<span class='footer-external-link'>GitHub</span>"
        href: "https://github.com/ShardulJunagade"
      - text: "<span class='footer-external-link'>Email</span>"
        href: "mailto:shardul.junagade@gmail.com"
      - text: "<span class='footer-external-link'>LinkedIn</span>"
        href: "https://linkedin.com/in/shardul-junagade"
      # - text: "<span class='footer-external-link'>WhatsApp</span>"
      #   href: "https://wa.me/YOURNUMBER"
      - text: "<span class='footer-external-link'>X</span>"
        href: "https://x.com/Sh4rdulX"

format:
  html:
    smooth-scroll: true
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Poppins" type="text/css"/>
    mainfont: Poppins, sans-serif
    # monofont: JetBrainsMono, monospace (not needed)

execute:
  freeze: auto
